### ISSUE TITLE
Async mocks throws error

### ISSUE THREAD

**Issue by SvetlovA** [SvetlovA/static-mock#10]
Async methods mock throws, on all test execution:
```
Exit code is -532462766 (Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at StaticMock.Tests.ReturnsTests.GenericSetupMockReturnsAsyncTests.<>c__DisplayClass5_0.<<TestGenericSetupReturnsWithTestMethodReturnParameterFuncAsync>b__1>d.MoveNext() in D:\MyProjects\static-mock\src\StaticMock.Tests\ReturnsTests\GenericSetupMockReturnsAsyncTests.cs:line 102
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
```

**Comment by SvetlovA** [comment]
Was reproduce only in branch "HookParametrizeFunctions" and was already fixed as a part of parametrized hook feature
